"""Type stub for the parts of Cua Bench the task set uses (https://cua.ai/docs/cua-bench).

The real package is installed only where tasks run (``pip install cua-bench``); this stub keeps
``eval/tasks/computer_use/main.py`` type-checked without it and documents the assumed surface:
``Task``, ``DesktopSession`` and the four split-scoped decorators.
"""

from collections.abc import Awaitable, Callable
from typing import TypeVar

_F = TypeVar("_F", bound=Callable[..., object])

class Task:
    description: str
    task_id: str
    metadata: dict[str, object]
    computer: dict[str, object]
    def __init__(self, description: str, task_id: str = ..., metadata: dict[str, object] = ...,
                 computer: dict[str, object] = ...) -> None: ...

class DesktopSession:
    async def run_command(self, cmd: str, check: bool = ...) -> object: ...
    async def read_file(self, path: str) -> str: ...
    async def write_file(self, path: str, content: str) -> None: ...
    async def file_exists(self, path: str) -> bool: ...
    async def launch_window(self, html: str = ..., title: str = ...) -> object: ...
    async def execute_javascript(self, pid: object, script: str) -> object: ...
    async def screenshot(self) -> bytes: ...

def tasks_config(split: str = ...) -> Callable[[_F], _F]: ...
def setup_task(split: str = ...) -> Callable[[_F], _F]: ...
def evaluate_task(split: str = ...) -> Callable[[_F], _F]: ...
def solve_task(split: str = ...) -> Callable[[_F], _F]: ...

_Unused = Awaitable[None]
